version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - docker build -t myimage .
      - docker tag myimage:latest 012345678910.dkr.ecr.us-west-2.amazonaws.com/myrepo:latest
  post_build:
    commands:
      - docker push 012345678910.dkr.ecr.us-west-2.amazonaws.com/myrepo:latest
