version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 464612618574.dkr.ecr.ap-southeast-2.amazonaws.com/mygymprogressapi
  build:
    commands:
      - echo Building the Docker image...
      - cd MyGymProgressApi
      - docker build -t 464612618574.dkr.ecr.ap-southeast-2.amazonaws.com/mygymprogressapi:latest -f Dockerfile .
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 464612618574.dkr.ecr.ap-southeast-2.amazonaws.com/mygymprogressapi:latest
      - echo Build and push completed successfully!
      - echo "Listing contents of /app/publish"
      - ls -al /app/publish
